Return duplicade HTTP header fields in remote as array.
getkirby/toolkit pull request #237
Opened 2017-05-30 09:01 UTC by Zegnat

Fixes #234 per discussion in #235. No header field name normalisation,
but no more loss of data.

2017-06-02 19:31 UTC, lukasbestle requested changes
Looks good generally, thanks!
We won't merge this in 2.4.2 though as this is a breaking change.

2017-06-02 19:31 UTC, lukasbestle commented on lib/remote.php
> +      if (empty($this->headers[$key])) {
Please use `!isset()` here. `empty()` behaves quite strangely.

2017-06-03 11:38 UTC, Zegnat commented on lib/remote.php
> +      if (empty($this->headers[$key])) {
Done, that was silly of me, I know it would have failed on strings like `0`.

2017-06-03 13:50 UTC, lukasbestle approved these changes
Thanks, looks good now.

2020-01-14 08:51 UTC, closed without merging